In [2]:
import numpy as np

## 1. arange

In [2]:
l = range(100000)
d= np.arange(100000)

In [3]:
%time for i in range(1,10):r = [x*2 for x in l]

Wall time: 88.1 ms


In [4]:
%time for i in range(1,10):r = d*2

Wall time: 4 ms


## 2. zeros

In [5]:
x= np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3. ones

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 4. empty

In [9]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 5. array

In [10]:
l = [1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [13]:
x = np.arange(1,100,10)

## 6. shape

In [14]:
x.shape

(10,)

In [15]:
x = np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## 7. reshape

In [16]:
x.reshape((2,2,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

## 8. dtype

In [17]:
x.dtype

dtype('float64')

## 9. ndim

In [19]:
x.ndim

2

## 10. random.randn

In [24]:
a = np.random.randn((10))
b = np.random.randn((10))

In [25]:
a + b

array([-0.68834471, -0.53866138, -0.45229271,  2.82152908, -2.19614881,
        0.43056765, -4.49179545, -0.79847996, -0.19766303, -0.12735633])

In [26]:
2 * a

array([-0.7464664 , -1.40263178,  0.84066392,  1.63168383, -2.93237923,
        1.09829055, -3.64409396,  0.89316333, -0.7279874 ,  2.14619058])

In [27]:
a>0

array([False, False,  True,  True, False,  True, False,  True, False,
        True])

In [28]:
a[a>0]

array([0.42033196, 0.81584191, 0.54914528, 0.44658167, 1.07309529])

In [29]:
x = np.array([1,3,5,6,7,9])

In [30]:
x[x>5]

array([6, 7, 9])

In [33]:
x[[2,1,0]]

array([5, 3, 1])

In [35]:
x = np.random.randn(10,10)

In [36]:
x[0]

array([-0.30625405,  2.30177381,  0.55177329, -0.8687419 ,  0.33995034,
       -0.20391826, -1.84358559, -0.94206331, -0.41895097, -1.82245174])

In [37]:
x[0][5]

-0.203918259217405

In [38]:
x

array([[-0.30625405,  2.30177381,  0.55177329, -0.8687419 ,  0.33995034,
        -0.20391826, -1.84358559, -0.94206331, -0.41895097, -1.82245174],
       [-1.25264896,  2.27811472,  0.04876301, -0.46881404,  0.9608883 ,
        -1.02896428,  0.29507674,  0.31815043, -0.4289771 , -1.42163436],
       [-0.1351536 , -0.8461701 , -0.33872357, -0.8774309 ,  0.02066288,
         0.25328864, -0.3874592 ,  2.24050607, -0.19269712,  0.44569039],
       [-2.37504884,  0.42309683,  1.22732624,  0.83523146,  0.65376083,
        -0.54322256, -1.08700877, -1.05400647, -0.86752561, -0.30195674],
       [-0.78920672, -0.1487769 , -1.16719557, -0.61159372,  0.87801121,
        -0.50957644, -1.66176153, -0.31704017, -0.69121906, -2.40440007],
       [-2.2107688 ,  0.17103553, -0.5606559 ,  0.37048644,  0.79871781,
         1.01343786,  0.02513186,  0.39729283,  0.96810848,  0.32975288],
       [ 0.45541211,  0.51058785,  0.19086038,  0.54599873,  1.20415946,
        -0.61418301, -0.01506668, -0.55434534

In [42]:
%time x[1:10:2]

Wall time: 0 ns


array([[-1.25264896,  2.27811472,  0.04876301, -0.46881404,  0.9608883 ,
        -1.02896428,  0.29507674,  0.31815043, -0.4289771 , -1.42163436],
       [-2.37504884,  0.42309683,  1.22732624,  0.83523146,  0.65376083,
        -0.54322256, -1.08700877, -1.05400647, -0.86752561, -0.30195674],
       [-2.2107688 ,  0.17103553, -0.5606559 ,  0.37048644,  0.79871781,
         1.01343786,  0.02513186,  0.39729283,  0.96810848,  0.32975288],
       [-0.05509312, -0.1145509 , -0.57980817, -0.05214775,  0.70157764,
        -2.78596474,  0.3955847 ,  1.1889951 , -0.3612921 ,  0.71301604],
       [-0.54931594,  1.72196186,  2.23511677,  0.5165583 , -0.54240151,
         0.98858599,  2.09173145, -0.37793661,  1.28416905,  1.20039689]])

In [43]:
%time x[::,0:4]

Wall time: 0 ns


array([[-0.30625405,  2.30177381,  0.55177329, -0.8687419 ],
       [-1.25264896,  2.27811472,  0.04876301, -0.46881404],
       [-0.1351536 , -0.8461701 , -0.33872357, -0.8774309 ],
       [-2.37504884,  0.42309683,  1.22732624,  0.83523146],
       [-0.78920672, -0.1487769 , -1.16719557, -0.61159372],
       [-2.2107688 ,  0.17103553, -0.5606559 ,  0.37048644],
       [ 0.45541211,  0.51058785,  0.19086038,  0.54599873],
       [-0.05509312, -0.1145509 , -0.57980817, -0.05214775],
       [ 0.48070879, -0.69842903, -1.13208271,  0.90101306],
       [-0.54931594,  1.72196186,  2.23511677,  0.5165583 ]])

In [44]:
x = np.ones((5,5))

In [45]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
x[1:-1,1:-1] = 0

In [48]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
x = np.array([10,3,34,5,3,2])

## 11. sqrt

In [50]:
np.sqrt(x)

array([3.16227766, 1.73205081, 5.83095189, 2.23606798, 1.73205081,
       1.41421356])

## 12. power

In [51]:
np.power(x,2)

array([ 100,    9, 1156,   25,    9,    4], dtype=int32)

In [52]:
y= [7,1,-1,4,6,7]

## 13. maximum

In [53]:
np.maximum(x,y)

array([10,  3, 34,  5,  6,  7])

In [54]:
salary = np.array([0,-1,100000,150000])

## 14. where

In [55]:
np.where(salary<=0,25000,salary)

array([ 25000,  25000, 100000, 150000])

In [56]:
np.where(salary<=0,"Not OK","OK")

array(['Not OK', 'Not OK', 'OK', 'OK'], dtype='<U6')

In [58]:
x

array([10,  3, 34,  5,  3,  2])

## 15. mean

In [59]:
x.mean()

9.5

## 16. cumsum

In [60]:
x.cumsum()

array([10, 13, 47, 52, 55, 57], dtype=int32)

## 17. cumprod

In [61]:
x.cumprod()

array([   10,    30,  1020,  5100, 15300, 30600], dtype=int32)

In [62]:
y = x>20

In [63]:
y

array([False, False,  True, False, False, False])

## 18. sum

In [64]:
y.sum()

1

## 19. any

In [65]:
y.any()

True

## 20. all

In [66]:
y.all()

False

In [67]:
x

array([10,  3, 34,  5,  3,  2])

## 21. sort

In [68]:
x.sort()

In [69]:
x

array([ 2,  3,  3,  5, 10, 34])

## 22. unique

In [71]:
np.unique(x)

array([ 2,  3,  5, 10, 34])

In [72]:
x = [1,4,5,7]
y = [8,7,9] 

## 23. save

In [73]:
np.save('testx',x)

## 24. load

In [75]:
loadx = np.load("testx.npy")

In [76]:
loadx

array([1, 4, 5, 7])

## 25. savez

In [86]:
np.savez("testxy",x=x,y=y)

In [87]:
loadxy = np.load("testxy.npz")
loadxy

In [89]:
loadxy['x']

array([1, 4, 5, 7])

In [93]:
x = np.random.randn(3,2)
y = np.random.randn(2,3)

## 26. dot

In [94]:
x.dot(y)

array([[ 2.38826667,  6.02023132, -0.43331457],
       [-1.34841438, -0.96911542, -0.36767849],
       [ 0.63424145,  2.42471765, -0.32321037]])

## 27. transpose

In [96]:
x.transpose()

array([[-2.13835427,  0.91843832, -0.66606532],
       [ 1.51290549,  0.53262196,  0.87316687]])

In [97]:
x

array([[-2.13835427,  1.51290549],
       [ 0.91843832,  0.53262196],
       [-0.66606532,  0.87316687]])

## 28. trace

In [98]:
x.trace()

-1.6057323047260366

## 29. random.seed
## 30. random.normal

In [100]:
np.random.seed(7)
np.random.normal(size=(3,2))

array([[ 1.6905257 , -0.46593737],
       [ 0.03282016,  0.40751628],
       [-0.78892303,  0.00206557]])

## 31. random.uniform

In [101]:
np.random.uniform(size = (3,2))

array([[0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904],
       [0.38094113, 0.06593635]])

In [106]:
x = np.random.randn(4,5)

In [107]:
x

array([[ 0.55458031,  0.12388091,  0.27445992, -1.52652453,  1.65069969],
       [ 0.15433554, -0.38713994,  2.02907222, -0.04538603, -1.4506787 ],
       [-0.40522786, -2.2883151 ,  1.04939655, -0.41647432, -0.74255353],
       [ 1.07247013, -1.65107559,  0.53542936, -2.0644148 , -0.66215934]])

In [108]:
x.reshape(2,2,5)

array([[[ 0.55458031,  0.12388091,  0.27445992, -1.52652453,
          1.65069969],
        [ 0.15433554, -0.38713994,  2.02907222, -0.04538603,
         -1.4506787 ]],

       [[-0.40522786, -2.2883151 ,  1.04939655, -0.41647432,
         -0.74255353],
        [ 1.07247013, -1.65107559,  0.53542936, -2.0644148 ,
         -0.66215934]]])

In [109]:
x.reshape(2,2,5,order= 'F')

array([[[ 0.55458031,  0.12388091,  0.27445992, -1.52652453,
          1.65069969],
        [-0.40522786, -2.2883151 ,  1.04939655, -0.41647432,
         -0.74255353]],

       [[ 0.15433554, -0.38713994,  2.02907222, -0.04538603,
         -1.4506787 ],
        [ 1.07247013, -1.65107559,  0.53542936, -2.0644148 ,
         -0.66215934]]])

In [111]:
x.reshape(2,-1,5)

array([[[ 0.55458031,  0.12388091,  0.27445992, -1.52652453,
          1.65069969],
        [ 0.15433554, -0.38713994,  2.02907222, -0.04538603,
         -1.4506787 ]],

       [[-0.40522786, -2.2883151 ,  1.04939655, -0.41647432,
         -0.74255353],
        [ 1.07247013, -1.65107559,  0.53542936, -2.0644148 ,
         -0.66215934]]])

## 32. ravel

In [112]:
x.ravel()

array([ 0.55458031,  0.12388091,  0.27445992, -1.52652453,  1.65069969,
        0.15433554, -0.38713994,  2.02907222, -0.04538603, -1.4506787 ,
       -0.40522786, -2.2883151 ,  1.04939655, -0.41647432, -0.74255353,
        1.07247013, -1.65107559,  0.53542936, -2.0644148 , -0.66215934])

## 33. flatten

In [113]:
x.flatten()

array([ 0.55458031,  0.12388091,  0.27445992, -1.52652453,  1.65069969,
        0.15433554, -0.38713994,  2.02907222, -0.04538603, -1.4506787 ,
       -0.40522786, -2.2883151 ,  1.04939655, -0.41647432, -0.74255353,
        1.07247013, -1.65107559,  0.53542936, -2.0644148 , -0.66215934])

In [114]:
x = [[1,3,5],[7,9,0]]
y = [[11,13,15],[17,19,10]]

In [115]:
np.array(x)
np.array(y)

array([[11, 13, 15],
       [17, 19, 10]])

## 34. concatenate

In [122]:
%time np.concatenate((x,y),axis = 0)

Wall time: 0 ns


array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [118]:
np.concatenate((x,y),axis = 1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

## 35. vstack

In [123]:
%time np.vstack((x,y))

Wall time: 0 ns


array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

## 36. hstack

In [121]:
np.hstack((x,y))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [124]:
x=[1,3,6,7,4,6,8]
d = np.array(x)

## 37. split

In [125]:
np.split(d,[3,5])

[array([1, 3, 6]), array([7, 4]), array([6, 8])]

In [126]:
x=[[1,3,6,7,4,6,8],[11,13,16,17,14,16,18]]
d = np.array(x)

In [128]:
np.split(d,[4,6],axis =1)

[array([[ 1,  3,  6,  7],
        [11, 13, 16, 17]]), array([[ 4,  6],
        [14, 16]]), array([[ 8],
        [18]])]

In [129]:
np.split(d,[1])

[array([[1, 3, 6, 7, 4, 6, 8]]), array([[11, 13, 16, 17, 14, 16, 18]])]

## 38. repeat

In [130]:
d = np.array([1,3,5,7,9])
np.repeat(d,3)

array([1, 1, 1, 3, 3, 3, 5, 5, 5, 7, 7, 7, 9, 9, 9])

## 39. tile

In [131]:
np.tile(d,3)

array([1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9])

In [3]:
l = np.array([1,2,3,5,6,7,8])

## 40. itemsize

In [4]:
l.itemsize

4

## 41. size

In [5]:
l.size

7

## 42. min

In [6]:
l.min()

1

## 43. max

In [7]:
l.max()

8

## 44. diag

In [8]:
np.diag(l)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 8]])

## 45. identity

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 46. random.randint

In [13]:
np.random.randint(3,size = 5)

array([0, 2, 0, 2, 0])

In [14]:
np.random.randint(3,size = (5,5))

array([[0, 1, 0, 0, 2],
       [1, 0, 2, 2, 2],
       [2, 0, 0, 1, 1],
       [2, 1, 2, 0, 1],
       [2, 2, 0, 0, 0]])

## 47. sin

In [15]:
np.sin(l)

array([ 0.84147098,  0.90929743,  0.14112001, -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825])

## 48. cos

In [16]:
np.cos(l)

array([ 0.54030231, -0.41614684, -0.9899925 ,  0.28366219,  0.96017029,
        0.75390225, -0.14550003])

## 49. tan

In [17]:
np.tan(l)

array([ 1.55740772, -2.18503986, -0.14254654, -3.38051501, -0.29100619,
        0.87144798, -6.79971146])

## 50. log

In [18]:
np.log(l)

array([0.        , 0.69314718, 1.09861229, 1.60943791, 1.79175947,
       1.94591015, 2.07944154])